name: masa_takip_sistemi
description: Masa Takip Sistemi – yerel veritabanı kullanan masa, ürün ve sipariş yönetimi.

version: 3.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  provider: ^6.1.2
  # fl_chart: ^0.68.0 # Raporlar sayfası için daha sonra eklenecek
  intl: ^0.18.1
  uuid: ^4.5.1
  fl_chart: ^1.0.0
  shared_preferences: ^2.5.3
  reorderable_grid_view: ^2.2.8
  url_launcher: ^6.3.2
  cloud_firestore: ^6.0.2
  firebase_auth: ^6.1.0
  chewie: ^1.6.1
  video_player: ^2.6.0
  network_info_plus: ^5.0.0
  google_fonts: ^6.0.0
  animated_text_kit: ^4.2.2
  google_ml_kit: ^0.20.0
  #camera: ^0.11.2
  tflite_flutter: ^0.11.0
  image_picker: ^0.8.7+4
  flutter_vlc_player: ^7.4.0
  local_auth: ^2.3.0
  google_mlkit_face_detection: ^0.13.1
  flutter_secure_storage: ^9.2.4
  shimmer: ^3.0.0
  open_file: ^3.3.2 # Dosyaları açmak için
  flutter_pdfview: ^1.3.2 # Uygulama içi PDF görüntüleme için
  pdf: ^3.10.8
  printing: ^5.12.0
  pdfx: ^2.5.0
  workmanager: ^0.9.0+3
  showcaseview: ^5.0.1
  syncfusion_flutter_pdfviewer: ^31.2.3
  material_design_icons_flutter: ^7.0.7296
  qr_flutter: ^4.1.0
  flutter_html: ^3.0.0
  share_plus: ^12.0.1
  google_generative_ai: ^0.4.7
  flutter_dotenv: ^6.0.0
  flutter_gemini: ^3.0.0
  flutter_tts: ^4.2.3
  pub_semver: ^2.2.0
  google_mlkit_text_recognition: ^0.15.0

dependency_overrides:
  image: ^4.0.17
  #camera_avfoundation: 0.9.15+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.12.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/metsoft.png
    - assets/modern.jpg
    - assets/guvenilir.jpg
    - assets/kullanici-odakli.jpg
    - assets/fonts/Roboto-Regular.ttf
    - assets/fonts/Roboto-Bold.ttf
    - assets/fonts/Roboto-Italic.ttf
    - assets/fonts/Roboto-BoldItalic.ttf
    - .env
   #- assets/embeddinggemma-300M_seq1024_mixed-precision.tflite
   #- assets/sentencepiece.model
   
# Bu bölüm doğru ve değiştirilmedi
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"